version: '2'

services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop_b1c0sl
    hostname: prestashop_ossd
    restart: always
    ports:
      - 8080:80
    environment:
      - PS_DEV_MODE=false 
      - PS_INSTALL_AUTO=0
    volumes:
      - /Volumes/PRESTADB/WFS/:/var/www/html
    network_mode: "host"
  
#networks:
#  prestashop_network:
#    driver: bridge
