version: '2'

services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop_b1c0sl
    hostname: internal_prestahop
    restart: always
    ports:
      - 8080:80
    environment:
      - PS_DEV_MODE=false 
      - PS_INSTALL_AUTO=0
    volumes:
      - /Volumes/PRESTADB/WFS/:/var/www/html
  mysql:
    image: mysql:latest
    container_name: db_mysql_all
    hostname: db_mysqlserver
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= systemsutilsmysql
      - MYSQL_DATABASE= presto
      - MYSQL_USER = prestashop_admin
      - MYSQL_PASSWORD = 12345aA.
    volumes:
      - /Volumes/PRESTADB/DB:/var/lib/mysql
      - /Volumes/PRESTADB/init_DB.sql:/docker-entrypoint-initdb.d
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro