version: '2'

services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop_b1c0sl
    hostname: prestashop_ossd
    restart: always
   # networks: 
   #   - prestashop_network
    ports:
      - 8080:80
    environment:
      - PS_DEV_MODE=false 
      - PS_INSTALL_AUTO=0
    volumes:
      - /Volumes/PRESTADB/WFS/:/var/www/html
  mysql:
    image: mysql:5.7.28
    container_name: db_mysql_all
    hostname: db_mysqlserver
    restart: always
    #networks:
    #  - prestashop_network
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= utildb2022
      - MYSQL_DATABASE= prestashop
      - MYSQL_USER= prestoadmin
      - MYSQL_PASSWORD= 12345aA
    volumes:
      - /Volumes/PRESTADB/DB:/var/lib/mysql
      - /Volumes/PRESTADB/init_DB.sql:/docker-entrypoint-initdb.d
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

#networks:
#  prestashop_network:
#    driver: bridge
