version: '2'

services:
  mysql:
    image: mysql:5.7.36
    container_name: mysql_moodle
    hostname: MoodleServer
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=moodleroot
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=12345aA
    volumes:
      - /Volumes/MoodleDB/:/var/lib/mysql
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: "host"