version: '2'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_moodle
    hostname: MoodleServer
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=moodleroot
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=12345aA
    command: --innodb_log_file_size=16M --join_buffer_size=1M --tmp_table_size=128M --max_heap_table_size=256M
    volumes:
      - /Volumes/MoodleDB/db:/var/lib/mysql
      - /Volumes/MoodleDB/conf:/etc/my.cnf
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: "host"