version: '2'

services:
  mysql:
   image: mysql:latest
    container_name: db_mysql_add
    hostname: db_mysqlserver
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= systemsutilsmysql
      - MYSQL_DATABASE= django
      - MYSQL_USER = django_admin
      - MYSQL_PASSWORD = 12345aA.
    volumes:
      - /Volumes/MYSQL_DJANGO/DB:/var/lib/mysql
      - /Volumes/MYSQL_DJANGO/init_DB.sql:/docker-entrypoint-initdb.d
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro



