apt remove php7.4-cli -y
apt remove php7.4 -y
apt remove php-zip -y
apt remove php7.4-xml -y
apt remove php7.4-curl -y
apt remove php7.4-gd -y
apt remove php7.4-mysql -y
apt remove php-mbstring -y
apt remove php-intl -y
apt purge php7.4-cli -y
apt purge php7.4 -y
apt purge php-zip -y
apt purge php7.4-xml -y
apt purge php7.4-curl -y
apt purge php7.4-gd -y
apt purge php7.4-mysql -y
apt purge php-mbstring -y
apt purge php-intl -y