version: '2'

services:
  portainer:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: microsoft_sqlserver
    hostname: mrsft_sqlsrv
    restart: always
    ports:
      - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=complexityofyourdecisions@123home
        - MSSQL_PID= DEVELOPER
    volumes:
      - /volumes/microsoft/mssql:/var/opt/mssql/
      
      
